"""Offline ShadowPad/ScatterBee payload and configuration extractor.

The implementation is derived from the public PwC ScatterBee description and
uses only byte transformations.  It never loads a PE, executes shellcode, or
contacts a recovered endpoint.
"""

from __future__ import annotations

import hashlib
import ipaddress
import re
import struct
from dataclasses import dataclass
import urllib.parse

import pefile
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

from extractors.common import build_result, sha256_bytes
from extractors.shadowpad.legacy import decode_legacy_pe, find_legacy_configs


STREAM_SUB_KEYS = (
    0x53335D9F,
    0xEF819993,
    0x0E8589FF,
    0x0DC7F607,
    0x443246BA,
    0x56AB233F,
)
AES_KEY_STRINGS = (
    bytes.fromhex("82e4e2fef155d09e01b798ff318c0af8"),
    bytes.fromhex("3988a18dbae0d9f1b15fafc7621e0d80"),
    bytes.fromhex("f0c2c5c7d0d95fd758aeabcb6b40c2cb"),
    bytes.fromhex("65660daf6515d3b7557c7364655995f4"),
)
CONFIG_32_LABELS = (
    "timestamp",
    "campaign_code",
    "install_path",
    "spoofed_name",
    "loader_filename",
    "payload_filename",
    "service_name",
    "alternative_service_name_1",
    "alternative_service_name_2",
    "registry_key_path",
    "service_description",
    "injection_target_1",
    "injection_target_2",
    "injection_target_3",
    "injection_target_4",
    "c2_1",
    "c2_2",
    "c2_3",
    "c2_4",
    "proxy_1",
    "proxy_2",
    "proxy_3",
    "proxy_4",
)
VALID_CHUNK_TAGS = {0x02, 0x80, 0x83, 0x84, 0x90, 0x91, 0x92, 0xA0}
NETWORK_VALUE = re.compile(
    r"(?i)(?:tcp|udp|http|https)://[^\s\x00]+|"
    r"(?<![\w.-])(?:[a-z0-9-]+\.)+[a-z]{2,63}:\d{1,5}|"
    r"(?<![\d.])(?:\d{1,3}\.){3}\d{1,3}:\d{1,5}"
)


@dataclass(frozen=True)
class PayloadDecode:
    """A successfully decoded ScatterBee payload."""

    data: bytes
    algorithm: str
    key_id: str


def add_seed_bytes(value: int) -> int:
    """Return the low byte of the sum of a 32-bit seed's four bytes."""
    return sum((value >> shift) & 0xFF for shift in (0, 8, 16, 24)) & 0xFF


def scatter_stream(data: bytes, seed: int, sub_key: int) -> bytes:
    """Decode bytes with the ScatterBee evolving-seed stream cipher."""
    output = bytearray(len(data))
    for index, value in enumerate(data):
        seed = ((17 * seed) - sub_key) & 0xFFFFFFFF
        output[index] = value ^ add_seed_bytes(seed)
    return bytes(output)


def derive_aes_key(md5_digest: bytes) -> bytes:
    """Reproduce the AES-128 key material generated by CryptoAPI."""
    inner = bytes(value ^ 0x36 for value in md5_digest) + b"\x36" * (
        64 - len(md5_digest)
    )
    outer = bytes(value ^ 0x5C for value in md5_digest) + b"\x5c" * (
        64 - len(md5_digest)
    )
    return hashlib.md5(inner).digest() + hashlib.md5(outer).digest()


def _aligned_ciphertext(data: bytes) -> bytes:
    """Pad malformed final blocks in the same tolerant way as public tooling."""
    missing = (-len(data)) % 16
    return data if not missing else data + bytes([missing]) * missing


def scatter_aes(data: bytes, key_string: bytes) -> bytes:
    """Decrypt an MD5/CryptoDeriveKey ScatterBee AES payload."""
    if len(data) < 20:
        raise ValueError("AES payload is too short")
    seed = data[-4:]
    key = derive_aes_key(hashlib.md5(key_string + seed).digest())[:16]
    decryptor = Cipher(algorithms.AES(key), modes.CBC(bytes(16))).decryptor()
    return decryptor.update(_aligned_ciphertext(data[:-4])) + decryptor.finalize()


def decode_payload(data: bytes) -> PayloadDecode | None:
    """Decode a complete ScatterBee payload when a known key variant matches."""
    if len(data) < 20:
        return None
    seed = struct.unpack_from("<I", data)[0]
    for sub_key in STREAM_SUB_KEYS:
        prefix = scatter_stream(data[4:9], seed, sub_key)
        if len(prefix) == 5 and prefix[0] == 0xE9 and prefix[4] == 0:
            return PayloadDecode(
                scatter_stream(data[4:], seed, sub_key), "stream", f"0x{sub_key:08x}"
            )
    for index, key_string in enumerate(AES_KEY_STRINGS):
        try:
            decoded = scatter_aes(data, key_string)
        except ValueError:
            continue
        if len(decoded) >= 5 and decoded[0] == 0xE9 and decoded[4] == 0:
            return PayloadDecode(decoded, "aes-md5", f"known-key-{index + 1}")
    return None


def _decode_text(data: bytes) -> str:
    """Render decoded configuration bytes without silently discarding data."""
    value = data.rstrip(b"\x00")
    for encoding in ("utf-8", "utf-16le", "latin-1"):
        try:
            return value.decode(encoding).rstrip("\x00")
        except (UnicodeDecodeError, UnicodeError):
            continue
    return value.hex()


def _decode_stream_entry(
    config: bytes, relative_offset: int, sub_key: int, base: int
) -> str:
    """Decode one seed/length/data configuration entry."""
    offset = base + relative_offset
    if offset < 0 or offset + 4 > len(config):
        raise ValueError("configuration string offset is outside the buffer")
    seed, length = struct.unpack_from("<HH", config, offset)
    end = offset + 4 + length
    if end > len(config):
        raise ValueError("configuration string length is outside the buffer")
    return _decode_text(scatter_stream(config[offset + 4 : end], seed, sub_key))


def find_32_config(payload: bytes) -> int | None:
    """Find and structurally validate a 32-bit ShadowPad configuration."""
    marker = b"\x08" * 16
    start = 0
    while True:
        marker_offset = payload.find(marker, start)
        if marker_offset < 0:
            return None
        config_offset = marker_offset - 0x7A
        if config_offset >= 0 and config_offset + 0xBE <= len(payload):
            code_size, data_size, patch_size = struct.unpack_from(
                "<III", payload, config_offset + 0x18
            )
            if code_size + data_size + patch_size == config_offset:
                return config_offset
        start = marker_offset + 1


def parse_32_config(payload: bytes, sub_key: int) -> dict | None:
    """Decode the documented 23-string 32-bit ShadowPad configuration."""
    offset = find_32_config(payload)
    if offset is None:
        return None
    config = payload[offset:]
    code_size, data_size, patch_size = struct.unpack_from("<III", config, 0x18)
    operating_mode = struct.unpack_from("<I", config, 0x28)[0]
    relative_offsets = [
        struct.unpack_from("<H", config, 0x34 + 2 * index)[0] for index in range(19)
    ]
    relative_offsets += [
        struct.unpack_from("<H", config, 0x72 + 2 * index)[0] for index in range(4)
    ]
    values: dict[str, str] = {}
    for label, relative in zip(CONFIG_32_LABELS, relative_offsets, strict=True):
        try:
            values[label] = _decode_stream_entry(config, relative, sub_key, 0xBE)
        except ValueError:
            values[label] = ""
    return {
        "format": "shadowpad-32",
        "offset": offset,
        "code_size": code_size,
        "data_size": data_size,
        "patch_size": patch_size,
        "operating_mode": operating_mode,
        "strings": values,
    }


def find_64_chunks(payload: bytes) -> int | None:
    """Find three consecutive valid 64-bit ShadowPad chunk headers."""
    limit = len(payload) - 12
    for offset in range(max(0, limit)):
        first = struct.unpack_from("<I", payload, offset)[0]
        if first >> 24 != 0x80:
            continue
        cursor = offset
        valid = True
        for _ in range(3):
            if cursor + 4 > len(payload):
                valid = False
                break
            header = struct.unpack_from("<I", payload, cursor)[0]
            tag, length = header >> 24, header & 0xFFFFFF
            if (
                tag not in VALID_CHUNK_TAGS
                or not length
                or cursor + 4 + length > len(payload)
            ):
                valid = False
                break
            cursor += 4 + length
        if valid:
            return offset
    return None


def _strip_pkcs7(data: bytes) -> bytes:
    """Remove valid PKCS#7 padding and preserve all other byte strings."""
    if data and 0 < data[-1] <= 16 and data.endswith(bytes([data[-1]]) * data[-1]):
        return data[: -data[-1]]
    return data


def _aes_config_string(data: bytes, key_string: bytes) -> str:
    """Decode one AES-encrypted 64-bit ShadowPad configuration string."""
    if len(data) < 4:
        raise ValueError("AES config string is too short")
    encoded_length, encoded_seed = struct.unpack_from("<HH", data)
    length = encoded_length ^ ((encoded_seed - 0x92F) & 0xFFFF)
    ciphertext = data[4 : 4 + length]
    if not ciphertext or 4 + length > len(data):
        raise ValueError("AES config string length is invalid")
    digest = hashlib.md5(key_string + data[2:4]).digest()
    key = derive_aes_key(digest)[:16]
    decryptor = Cipher(algorithms.AES(key), modes.CBC(bytes(16))).decryptor()
    decoded = decryptor.update(_aligned_ciphertext(ciphertext)) + decryptor.finalize()
    return _decode_text(_strip_pkcs7(decoded))


def parse_64_config(payload: bytes, decode: PayloadDecode) -> dict | None:
    """Decode a supported AES or stream-cipher 64-bit ShadowPad config chunk."""
    chunk_offset = find_64_chunks(payload)
    if chunk_offset is None:
        return None
    header = struct.unpack_from("<I", payload, chunk_offset)[0]
    length = header & 0xFFFFFF
    body = payload[chunk_offset + 4 : chunk_offset + 4 + length]
    marker = b"\x08" * 6 + b"\x04" * 7 + b"\x02" * 3
    decoded_config: bytes | None = None
    strings: list[str] = []
    encoding = "unknown"
    for key_string in AES_KEY_STRINGS:
        try:
            candidate = scatter_aes(body, key_string)
        except ValueError:
            continue
        if marker not in candidate:
            continue
        decoded_config, encoding = candidate, "aes-md5"
        for index in range(23):
            relative = struct.unpack_from("<H", candidate, 4 + 2 * index)[0]
            try:
                strings.append(
                    _aes_config_string(candidate[0x331 + relative :], key_string)
                )
            except (ValueError, struct.error):
                strings.append("")
        for index in range(4):
            relative = struct.unpack_from("<H", candidate, 0x50 + 2 * index)[0]
            try:
                strings.append(
                    _aes_config_string(candidate[0x331 + relative :], key_string)
                )
            except (ValueError, struct.error):
                strings.append("")
        break
    if decoded_config is None and decode.algorithm == "stream":
        sub_key = int(decode.key_id, 16)
        if len(body) >= 4:
            seed = struct.unpack_from("<I", body)[0]
            candidate = scatter_stream(body[4:], seed, sub_key)
            if marker in candidate:
                decoded_config, encoding = candidate, "stream"
                for index in range(19):
                    relative = struct.unpack_from("<H", candidate, 2 * index)[0]
                    try:
                        strings.append(
                            _decode_stream_entry(candidate, relative, sub_key, 0x366)
                        )
                    except ValueError:
                        strings.append("")
                for table_offset in (0x4C, 0x3E):
                    for index in range(4):
                        relative = struct.unpack_from(
                            "<H", candidate, table_offset + 2 * index
                        )[0]
                        try:
                            strings.append(
                                _decode_stream_entry(
                                    candidate, relative, sub_key, 0x366
                                )
                            )
                        except ValueError:
                            strings.append("")
    if decoded_config is None:
        return None
    return {
        "format": "shadowpad-64",
        "offset": chunk_offset,
        "chunk_length": length,
        "config_encoding": encoding,
        "strings": {
            f"config_string_{index + 1:02d}": value
            for index, value in enumerate(strings)
        },
    }


def _pe_regions(data: bytes) -> list[tuple[str, bytes]]:
    """Return PE resources and high-entropy data sections as decode candidates."""
    regions: list[tuple[str, bytes]] = []
    try:
        pe = pefile.PE(data=data, fast_load=False)
    except pefile.PEFormatError:
        return regions
    for section in pe.sections:
        name = section.Name.rstrip(b"\x00").decode("ascii", errors="replace")
        if name.lower() in {".rdata", ".data", ".rsrc"} or name.lower().startswith(
            ".nsp"
        ):
            raw = section.get_data()
            if raw:
                regions.append((f"section:{name}", raw))
    if hasattr(pe, "DIRECTORY_ENTRY_RESOURCE"):
        for type_entry in pe.DIRECTORY_ENTRY_RESOURCE.entries:
            for name_entry in type_entry.directory.entries:
                for lang_entry in name_entry.directory.entries:
                    rva = lang_entry.data.struct.OffsetToData
                    size = lang_entry.data.struct.Size
                    raw = pe.get_memory_mapped_image()[rva : rva + size]
                    if raw:
                        regions.append(
                            (
                                f"resource:{type_entry.struct.Id}/{name_entry.struct.Id}",
                                raw,
                            )
                        )
    return regions


def decode_candidates(data: bytes) -> list[tuple[str, PayloadDecode]]:
    """Decode the input or any PE region that contains a full ScatterBee payload."""
    candidates = [("input", data)] + _pe_regions(data)
    output: list[tuple[str, PayloadDecode]] = []
    seen: set[str] = set()
    for source, candidate in candidates:
        digest = sha256_bytes(candidate)
        if digest in seen:
            continue
        seen.add(digest)
        decoded = decode_payload(candidate)
        if decoded is not None:
            output.append((source, decoded))
    return output


def network_values(config: dict) -> list[str]:
    """Extract unique endpoint-like values from decoded config strings."""
    strings = config.get("strings", {})
    values = strings.values() if isinstance(strings, dict) else strings
    return sorted(
        {
            match.group().rstrip(".,;)")
            for value in values
            for match in NETWORK_VALUE.finditer(str(value))
        }
    )


def _network_role(value: str) -> str:
    """Keep private builder/test addresses out of publishable C2 lists."""
    try:
        host = urllib.parse.urlsplit(value).hostname
        if host and ipaddress.ip_address(host).is_private:
            return "context_only_private_config"
    except ValueError:
        pass
    return "shadowpad_config_network"


def extract(data: bytes, name: str = "sample") -> dict:
    """Extract ShadowPad config evidence without executing or writing decoded data."""
    decoded_items = decode_candidates(data)
    recovered: list[dict] = []
    findings: list[dict] = []
    for source, decoded in decoded_items:
        sub_key = int(decoded.key_id, 16) if decoded.algorithm == "stream" else None
        config = parse_32_config(decoded.data, sub_key) if sub_key is not None else None
        config = config or parse_64_config(decoded.data, decoded)
        entry = {
            "source": source,
            "decoded_sha256": sha256_bytes(decoded.data),
            "algorithm": decoded.algorithm,
            "key_id": decoded.key_id,
            "config": config,
        }
        recovered.append(entry)
        if config:
            for value in network_values(config):
                findings.append(
                    {
                        "kind": "network.endpoint",
                        "value": value,
                        "role": _network_role(value),
                        "confidence": "confirmed",
                        "source": f"decoded_config:{source}",
                    }
                )
    legacy_items = decode_legacy_pe(data)
    for decoded in legacy_items:
        configs = find_legacy_configs(decoded.data, decoded.architecture)
        recovered.append(
            {
                "source": f"pe-rva:0x{decoded.encrypted_rva:x}",
                "decoded_sha256": sha256_bytes(decoded.data),
                "algorithm": f"casper-{decoded.architecture}-stream",
                "key_id": f"seed-rva:0x{decoded.seed_rva:x}",
                "module_offset": decoded.module_offset,
                "module_size": decoded.module_size,
                "configs": configs,
            }
        )
        for config in configs:
            for value in network_values(config):
                findings.append(
                    {
                        "kind": "network.endpoint",
                        "value": value,
                        "role": _network_role(value),
                        "confidence": "confirmed",
                        "source": f"legacy_config:0x{config['offset']:x}",
                    }
                )
    return build_result(
        "shadowpad",
        data,
        {
            "source_name": name,
            "decoded_payloads": recovered,
            "scatterbee_payload_count": len(decoded_items),
            "legacy_payload_count": len(legacy_items),
        },
        findings,
        [
            "Only public ScatterBee stream/AES key variants are supported.",
            "Casper-era x86/x64 streams, Config blocks, and QuickLZ level 1 are supported.",
            "Decoded payload bytes are hashed in memory but are not written by this extractor.",
            "No endpoint was contacted; config values describe static intent only.",
        ],
    )
